### ISSUE TITLE
Implement CI/CD Pipeline: Pre-commit Checks, Testing, and Multi-Arch Docker Build/Push

### ISSUE THREAD

**Issue by timthesinner** [timthesinner/smart-mcp-proxy#3]
## Objective
Establish a robust CI/CD pipeline for the `smart-mcp-proxy` repository using GitHub Actions, ensuring code quality, automated testing, and multi-architecture Docker image publishing.

---

### 1. Dockerfile Update
- **Location:** `docker/Dockerfile`
- **Requirements:**
  - Build the Go executable (targeting the main entrypoint, e.g., `cmd/proxy/main.go`).
  - Use a multi-stage build for minimal final image size (builder stage for Go build, final stage for runtime).
     - The final runtime layer must have NodeJS, Python3, as well as support for Docker in Docker 
  - Set the default `CMD` to run the built Go binary.
  - Ensure compatibility for both `amd64` and `arm64` architectures.

### 2. Pre-commit Checks (Run on Every Commit/PR)
- **Location:** `.github/workflows/ci.yml` (or similar)
- **Steps:**
  - **Go Formatting:**
    - Run `go fmt ./...`.
    - Fail the build if any files are not properly formatted.
  - **Go Tests:**
    - Run `go test ./...`.
    - Fail the build if any tests fail.
- **Branch Protection:**
  - These checks must pass before merging to `main` (enforce via branch protection rules).

### 3. Docker Build & Push (On Merge to Main)
- **Trigger:**
  - Only on push/merge to `main` branch.
  - Runs after pre-commit checks and tests succeed.
- **Steps:**
  - Build Docker images for both `linux/amd64` and `linux/arm64` using Docker Buildx.
  - Tag images as `ghcr.io/timthesinner/smart-mcp-proxy:latest` (and optionally with the commit SHA or version tag).
  - Push the multi-arch manifest to GitHub Container Registry (GHCR).
- **Secrets:**
  - Use `GHCR_TOKEN` or `GITHUB_TOKEN` for authentication to GHCR.

### 4. Example Workflow Structure
```yaml
name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Check formatting
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Run tests
        run: go test ./...
  docker:
    needs: pre-commit
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/timthesinner/smart-mcp-proxy:latest
```

### 5. Dependencies & Considerations
- **Go** (version as per `go.mod`)
- **Docker** with Buildx and QEMU support
- **GitHub Actions** runners
- **GHCR** for image storage
- **Branch protection rules** to enforce passing checks before merge

### 6. Acceptance Criteria
- [ ] Dockerfile builds a minimal, runnable image for both `amd64` and `arm64`.
- [ ] `go fmt ./...` and `go test ./...` run and must pass on all PRs/commits to `main`.
- [ ] On merge to `main`, a multi-arch Docker image is built and pushed to GHCR.
- [ ] All secrets and permissions for GHCR are correctly configured.
- [ ] Documentation in `README.md` is updated to describe the CI/CD process and how to pull/run the Docker image.

---

**References:**
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Docker Buildx](https://docs.docker.com/buildx/working-with-buildx/)
- [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)

---

This issue defines a complete, ready-to-implement CI/CD pipeline for the repository. All steps, dependencies, and acceptance criteria are included to enable immediate engineering action.
